name: Go
on: [push, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: build --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: windows_x86_64
          path: dist/packwiz_windows_amd64_v1/

      - uses: actions/upload-artifact@v4
        with:
          name: windows_i686
          path: dist/packwiz_windows_386_sse2/

      - uses: actions/upload-artifact@v4
        with:
          name: windows_aarch64
          path: dist/packwiz_windows_arm64_v8.0/

      - uses: actions/upload-artifact@v4
        with:
          name: linux_x86_64
          path: dist/packwiz_linux_amd64_v1/

      - uses: actions/upload-artifact@v4
        with:
          name: linux_i686
          path: dist/packwiz_linux_386_sse2/

      - uses: actions/upload-artifact@v4
        with:
          name: linux_aarch64
          path: dist/packwiz_linux_arm64_v8.0/

      - uses: actions/upload-artifact@v4
        with:
          name: darwin_x86_64
          path: dist/packwiz_darwin_amd64_v1/

      - uses: actions/upload-artifact@v4
        with:
          name: darwin_arm64
          path: dist/packwiz_darwin_arm64_v8.0/
