name: Go
on: [push, workflow_dispatch]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: '~> v2'
        args: --snapshot --skip publish --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/upload-artifact@v4
      with:
        name: Windows 64-bit
        path: dist/packwiz_windows_amd64_v1/

    - uses: actions/upload-artifact@v4
      with:
        name: Windows 32-bit
        path: dist/packwiz_windows_386_sse2/

    - uses: actions/upload-artifact@v4
      with:
        name: Windows 64-bit ARM
        path: dist/packwiz_windows_arm64_v8.0/

    - uses: actions/upload-artifact@v4
      with:
        name: Linux 64-bit x86
        path: dist/packwiz_linux_amd64_v1/

    - uses: actions/upload-artifact@v4
      with:
        name: Linux 32-bit x86
        path: dist/packwiz_linux_386_sse2/

    - uses: actions/upload-artifact@v4
      with:
        name: Linux 64-bit ARM
        path: dist/packwiz_linux_arm64_v8.0/

    - uses: actions/upload-artifact@v4
      with:
        name: macOS 64-bit x86
        path: dist/packwiz_darwin_amd64_v1/

    - uses: actions/upload-artifact@v4
      with:
        name: macOS 64-bit ARM
        path: dist/packwiz_darwin_arm64_v8.0/
